import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App : Home ",
  description: "Generated by create next app",
  authors: [{ name: "daniel Ouattara", url: "daniel.ouattara@gmx.com" }],
  icons: "./favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>My navbar</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
